name: blog_app
description: "A new Flutter project for blog sharing and exploration."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.2
  cloudinary_public: ^0.23.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: 12.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  google_sign_in: 6.3.0
  image_picker: ^1.2.0
  go_router: ^16.0.0
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  fluttertoast: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/svg/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
